version: '3'

services:
  volatility-viewer-ui:
    build: ./vol-client
    ports:
      - "3000:3000"
    container_name: volatility-viewer-ui
    stdin_open: true
    volumes:
       - ./vol-client:/usr/src/app/
       - /usr/src/app/node_modules