version: '3'
services:
  volatility-viewer-ui:
    build:
      context: ./vol-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: volatility-viewer-ui
    stdin_open: true
    volumes:
       - ./vol-client:/usr/src/app/vol-client
       - /usr/src/app/vol-client/node_modules